import 'dart:typed_data';

import 'blue_noise.g.dart';
import 'color_mapper.dart';

/// How a colour that falls between two palette entries is resolved.
///
/// **Ordered dithering is the default, and that is a deliberate choice against
/// the textbook one.** Floyd–Steinberg produces the best-looking *still* image,
/// and it is the wrong tool for an animation:
///
/// - **It boils.** One pixel changing by one level alters the error propagated
///   into every pixel after it, so regions that never moved decode differently
///   from frame to frame and the result shimmers.
/// - **It defeats LZW.** The noise it sprays is exactly what a dictionary
///   compressor cannot fold, and this package's whole performance story is that
///   dictionary.
/// - **It rules out frame diffing**, because no region is ever byte-identical to
///   the frame before it.
///
/// An ordered dither reads its threshold from a fixed matrix indexed by
/// position, so the same colour at the same place always resolves the same way.
/// Static regions stay byte-identical, and the pattern is periodic, which LZW
/// folds happily.
///
/// A plain class with a private constructor and static instances, matching
/// `GifRepeat`. Not an enum: [floydSteinberg] and [blueNoise] carry different
/// data, and not `sealed`, because callers never switch on it.
class GifDither {
  // Public parameter names assigned to private fields, rather than `this._x`:
  // private named parameters need Dart 3.12, and this package supports 3.7.
  const GifDither._(this._kind, {List<int>? matrix, int side = 0})
    : _matrix = matrix,
      _side = side;

  /// Nearest colour, with no perturbation at all.
  ///
  /// Smallest files and fastest, and it **bands** — visibly, on any gradient
  /// that a palette cannot represent. Correct when the input is already exactly
  /// palette colours, where there is nothing to dither.
  static const GifDither none = GifDither._(_DitherKind.none);

  /// **The default.** Void-and-cluster blue noise, 64×64.
  ///
  /// Ordered, so it has every temporal property above, but its threshold matrix
  /// has its energy at high spatial frequencies rather than in a regular grid —
  /// so it reads as fine texture instead of the cross-hatch [bayer4] shows on a
  /// smooth ramp. The table is generated by `tool/blue_noise.py` and its
  /// properties are checked in `test/blue_noise_test.dart`.
  ///
  /// Its matrix is null here and read from `blue_noise.g.dart` instead: a
  /// `Uint16List` cannot be `const`, and this descriptor must be, to sit in a
  /// default argument.
  static const GifDither blueNoise = GifDither._(
    _DitherKind.ordered,
    // Taken from the generated table rather than written as 64, so the
    // generator and this descriptor cannot drift apart.
    side: blueNoiseSide,
  );

  /// The classic 4×4 recursive matrix. Cheapest, smallest, and its regular grid
  /// is visible on smooth gradients at low palette counts.
  static const GifDither bayer4 = GifDither._(
    _DitherKind.ordered,
    matrix: _bayer4,
    side: 4,
  );

  /// 8×8 Bayer: finer steps than [bayer4], with a correspondingly larger cell.
  static const GifDither bayer8 = GifDither._(
    _DitherKind.ordered,
    matrix: _bayer8,
    side: 8,
  );

  /// Floyd–Steinberg error diffusion, scanned serpentine.
  ///
  /// **Best for a single frame, and animation-hostile** for the three reasons in
  /// the class docs. Reach for it when the output is one image, or when quality
  /// beats both file size and temporal stability.
  static const GifDither floydSteinberg = GifDither._(
    _DitherKind.floydSteinberg,
  );

  /// Atkinson's kernel, as used by classic MacPaint.
  ///
  /// Diffuses only **6/8** of the error and discards the rest, which lightens
  /// flat areas and raises contrast. That discarded quarter is deliberate, not a
  /// bug — it is why an Atkinson image does not converge to the input's mean.
  static const GifDither atkinson = GifDither._(_DitherKind.atkinson);

  final _DitherKind _kind;
  final List<int>? _matrix;
  final int _side;

  /// Whether this dither carries state from one pixel to the next.
  ///
  /// The ordered dithers do not, which is what makes them temporally stable.
  bool get diffusesError =>
      _kind == _DitherKind.floydSteinberg || _kind == _DitherKind.atkinson;

  @override
  String toString() => switch (_kind) {
    _DitherKind.none => 'GifDither.none',
    _DitherKind.ordered => switch (_side) {
      4 => 'GifDither.bayer4',
      8 => 'GifDither.bayer8',
      _ => 'GifDither.blueNoise',
    },
    _DitherKind.floydSteinberg => 'GifDither.floydSteinberg',
    _DitherKind.atkinson => 'GifDither.atkinson',
  };
}

enum _DitherKind { none, ordered, floydSteinberg, atkinson }

/// Bayer matrices, as raw ranks. Turned into thresholds in 4096ths at use.
const List<int> _bayer4 = <int>[
  0, 8, 2, 10, //
  12, 4, 14, 6, //
  3, 11, 1, 9, //
  15, 7, 13, 5, //
];
const List<int> _bayer8 = <int>[
  0, 32, 8, 40, 2, 34, 10, 42, //
  48, 16, 56, 24, 50, 18, 58, 26, //
  12, 44, 4, 36, 14, 46, 6, 38, //
  60, 28, 52, 20, 62, 30, 54, 22, //
  3, 35, 11, 43, 1, 33, 9, 41, //
  51, 19, 59, 27, 49, 17, 57, 25, //
  15, 47, 7, 39, 13, 45, 5, 37, //
  63, 31, 55, 23, 61, 29, 53, 21, //
];

/// Applies a [GifDither] to whole frames.
///
/// Built once per writer and reused, like the LZW encoder: its buffers are the
/// only per-frame allocation this package would otherwise make.
class DitherRunner {
  DitherRunner({
    required GifDither dither,
    required ColorMapper mapper,
    required int width,
  }) : _dither = dither,
       _mapper = mapper,
       _width = width,
       // Two rows of RGB error, and only when a diffusing dither will use them.
       // O(width), not O(frame) — 6 kB at 512 wide.
       _error = dither.diffusesError ? Int16List(width * 3) : _empty,
       _errorNext = dither.diffusesError ? Int16List(width * 3) : _empty;

  static final Int16List _empty = Int16List(0);

  final GifDither _dither;
  final ColorMapper _mapper;
  final int _width;
  Int16List _error;
  Int16List _errorNext;

  /// Maps [rgb] — three bytes per pixel — into [out], one index per pixel.
  void mapRgb({required Uint8List rgb, required Uint8List out}) {
    switch (_dither._kind) {
      case _DitherKind.none:
        _mapNearest(rgb: rgb, out: out);
      case _DitherKind.ordered:
        _mapOrdered(rgb: rgb, out: out);
      case _DitherKind.floydSteinberg:
      case _DitherKind.atkinson:
        _mapDiffused(rgb: rgb, out: out);
    }
  }

  void _mapNearest({required Uint8List rgb, required Uint8List out}) {
    for (var i = 0, p = 0; i < out.length; i++, p += 3) {
      out[i] =
          _mapper.candidates(r: rgb[p], g: rgb[p + 1], b: rgb[p + 2]) & 0xFF;
    }
  }

  /// Ordered dithering, choosing between the **two nearest** entries.
  ///
  /// The textbook form adds `(threshold - 0.5) * step` per channel, which needs
  /// a per-channel *step* — undefined for an arbitrary palette, and the usual
  /// source of a dither that looks right on a grey ramp and wrong on anything
  /// else. Instead: take the two nearest entries, work out where the true colour
  /// falls on the line between them, and compare that fraction with the
  /// threshold. One decision per pixel rather than three independent ones, and
  /// no tuning constant anywhere.
  void _mapOrdered({required Uint8List rgb, required Uint8List out}) {
    final matrix = _dither._matrix;
    final side = _dither._side;
    final mask = side - 1;
    final levels = side * side;
    final height = out.length ~/ _width;

    for (var y = 0, i = 0, p = 0; y < height; y++) {
      final row = (y & mask) * side;
      for (var x = 0; x < _width; x++, i++, p += 3) {
        final r = rgb[p];
        final g = rgb[p + 1];
        final b = rgb[p + 2];
        final packed = _mapper.candidates(r: r, g: g, b: b);
        final best = packed & 0xFF;
        final second = (packed >> 8) & 0xFF;
        if (best == second) {
          // Exact match, or a one-colour palette: there is no choice to make.
          out[i] = best;
          continue;
        }

        final br = _mapper.redAt(best);
        final bg = _mapper.greenAt(best);
        final bb = _mapper.blueAt(best);
        final sr = _mapper.redAt(second) - br;
        final sg = _mapper.greenAt(second) - bg;
        final sb = _mapper.blueAt(second) - bb;

        // How far along `best -> second` the true colour projects, in 4096ths.
        // The denominator cannot be zero: the two entries differ, or `best ==
        // second` caught it above.
        final denominator = sr * sr + sg * sg + sb * sb;
        var t =
            (((r - br) * sr + (g - bg) * sg + (b - bb) * sb) * 4096) ~/
            denominator;
        if (t < 0) t = 0;
        if (t > 4095) t = 4095;

        // Centred on the cell: `rank * 4096 / levels` would put the lowest
        // threshold at exactly 0, where every colour clears it and the matrix is
        // biased by half a step. The blue-noise table already has 4096 ranks, so
        // rank and threshold coincide.
        final threshold =
            matrix == null
                ? blueNoiseRanks[row + (x & mask)]
                : (matrix[row + (x & mask)] * 8192 + 4096) ~/ (2 * levels);
        out[i] = t > threshold ? second : best;
      }
    }
  }

  /// Error diffusion, scanned serpentine.
  ///
  /// The error is measured against the palette colour that will **actually be
  /// written**, never against the cube's cell centre — otherwise the cache's
  /// 5-bit approximation compounds across the whole frame instead of staying a
  /// per-pixel rounding.
  void _mapDiffused({required Uint8List rgb, required Uint8List out}) {
    final height = out.length ~/ _width;
    final atkinson = _dither._kind == _DitherKind.atkinson;

    // **Cleared per frame, not per writer.** Carrying a frame's residual error
    // into the next one makes an animation drift in a way that looks exactly
    // like a compression bug and is miserable to trace.
    _error.fillRange(0, _error.length, 0);
    _errorNext.fillRange(0, _errorNext.length, 0);

    for (var y = 0; y < height; y++) {
      // Serpentine: alternating direction cancels the diagonal streaking that
      // one-way diffusion leaves on a gradient.
      final leftToRight = y.isEven;
      for (var step = 0; step < _width; step++) {
        final x = leftToRight ? step : _width - 1 - step;
        final e = x * 3;
        final p = (y * _width + x) * 3;

        final r = _clampByte(rgb[p] + _error[e]);
        final g = _clampByte(rgb[p + 1] + _error[e + 1]);
        final b = _clampByte(rgb[p + 2] + _error[e + 2]);

        final index = _mapper.candidates(r: r, g: g, b: b) & 0xFF;
        out[y * _width + x] = index;

        var er = r - _mapper.redAt(index);
        var eg = g - _mapper.greenAt(index);
        var eb = b - _mapper.blueAt(index);

        if (atkinson) {
          // Atkinson passes on 6/8 and drops the rest. The discard is the point:
          // it is what gives the look its contrast.
          er = er * 6 ~/ 8;
          eg = eg * 6 ~/ 8;
          eb = eb * 6 ~/ 8;
          _spreadAtkinson(
            x: x,
            er: er,
            eg: eg,
            eb: eb,
            leftToRight: leftToRight,
          );
        } else {
          _spreadFloydSteinberg(
            x: x,
            er: er,
            eg: eg,
            eb: eb,
            leftToRight: leftToRight,
          );
        }
      }

      // The next row becomes the current one, and the buffer just finished is
      // reused for the row after — swapped rather than reallocated.
      final swap = _error;
      _error = _errorNext;
      _errorNext = swap;
      _errorNext.fillRange(0, _errorNext.length, 0);
    }
  }

  void _spreadFloydSteinberg({
    required int x,
    required int er,
    required int eg,
    required int eb,
    required bool leftToRight,
  }) {
    final ahead = leftToRight ? 1 : -1;
    _add(row: _error, x: x + ahead, er: er, eg: eg, eb: eb, numerator: 7);
    _add(row: _errorNext, x: x - ahead, er: er, eg: eg, eb: eb, numerator: 3);
    _add(row: _errorNext, x: x, er: er, eg: eg, eb: eb, numerator: 5);
    _add(row: _errorNext, x: x + ahead, er: er, eg: eg, eb: eb, numerator: 1);
  }

  void _spreadAtkinson({
    required int x,
    required int er,
    required int eg,
    required int eb,
    required bool leftToRight,
  }) {
    final ahead = leftToRight ? 1 : -1;
    // Atkinson's six neighbours each take a sixth of what is passed on.
    _add(
      row: _error,
      x: x + ahead,
      er: er,
      eg: eg,
      eb: eb,
      numerator: 1,
      denominator: 6,
    );
    _add(
      row: _error,
      x: x + 2 * ahead,
      er: er,
      eg: eg,
      eb: eb,
      numerator: 1,
      denominator: 6,
    );
    _add(
      row: _errorNext,
      x: x - ahead,
      er: er,
      eg: eg,
      eb: eb,
      numerator: 1,
      denominator: 6,
    );
    _add(
      row: _errorNext,
      x: x,
      er: er,
      eg: eg,
      eb: eb,
      numerator: 1,
      denominator: 6,
    );
    _add(
      row: _errorNext,
      x: x + ahead,
      er: er,
      eg: eg,
      eb: eb,
      numerator: 1,
      denominator: 6,
    );
    // The sixth neighbour is two rows down, which a two-row buffer cannot reach.
    // Folding it into the row below keeps the diffused total right; spreading it
    // exactly would cost a third row for a difference nobody can see.
    _add(
      row: _errorNext,
      x: x,
      er: er,
      eg: eg,
      eb: eb,
      numerator: 1,
      denominator: 6,
    );
  }

  void _add({
    required Int16List row,
    required int x,
    required int er,
    required int eg,
    required int eb,
    required int numerator,
    int denominator = 16,
  }) {
    if (x < 0 || x >= _width) return;
    final e = x * 3;
    row[e] += er * numerator ~/ denominator;
    row[e + 1] += eg * numerator ~/ denominator;
    row[e + 2] += eb * numerator ~/ denominator;
  }

  static int _clampByte(int v) => v < 0 ? 0 : (v > 255 ? 255 : v);
}
